### ISSUE TITLE
Timeout in Robot Server

### ISSUE THREAD

**Issue by AlchemicRonin** [wuphilipp/gello_software#1]
After running `python experiments/launch_nodes.py --robot=xarm` in the terminal, the program fails to control xArm and its output is shown below.
![Screenshot from 2023-11-24 19-21-32](https://github.com/wuphilipp/gello_software/assets/38276635/f6776a30-bf06-443a-9ef1-2e041effff59)
Also, running `python experiments/run_env.py --agent=gello` will not fix this problem.

**Comment by AlchemicRonin** [comment]
Problem solved.

**Comment by ruanjinchen** [comment]
Hello, I'm sorry to bother you. I would like to ask you where this problem occurred and how you solved it. I also encountered it.

**Comment by dayong233** [comment]
> 问题解决了。

Hello, I also encountered this problem. May I ask how you solved it?

**Comment by Navaneethakrishnan-S-M** [comment]
Hey @dayong233 and @ruanjinchen — hope you both managed to get it working by now, since it's been a while. But just in case it's still useful for anyone:

I ran into the same timeout issue:

```
Timeout in Robot Server, Robot: <gello.robots.xarm_robot.XArmRobot object at 0x7f596fd21720>
```

What worked for me was simply running:

```bash
python experiments/run_env.py --agent=gello
```

This resolved the timeout and got things moving. Hope it helps!
