### ISSUE TITLE
In the Dynamixel driver, why is torque mode turned on and then off?

### ISSUE THREAD

**Issue by GjermundOstensvig** [wuphilipp/gello_software#10]
Out of curiosity,
In the Dynamixel driver, why is torque mode turned on and then off?
```
    driver.set_torque_mode(True)
    driver.set_torque_mode(False)
```

**Comment by GjermundOstensvig** [comment]
I tried removing those two lines, and I'm still able to get_joints().

**Comment by wuphilipp** [comment]
Yeah that just tests that the functionality works. Added some comments in https://github.com/wuphilipp/gello_software/pull/11 to avoid future confusion!
