### ISSUE TITLE
ADDR_PRESENT_POSITION defined twice

### ISSUE THREAD

**Issue by adob** [wuphilipp/gello_software#3]
In [`driver.py`](https://github.com/wuphilipp/gello_software/blob/e6a660da6d13822d69cf96617b2448aecd1e1335/gello/dynamixel/driver.py#L18C1-L27C1), the variable `ADDR_PRESENT_POSITION` is defined twice:

```
# Constants
...
ADDR_PRESENT_POSITION = 132
ADDR_PRESENT_POSITION = 140
```

According to the [documentation](https://emanual.robotis.com/docs/en/dxl/x/xl330-m288/#control-table-of-ram-area), the "present position" variable is located at byte offset 132.

**Comment by wuphilipp** [comment]
Both work! Removed 140 in https://github.com/wuphilipp/gello_software/pull/11 to reduce confusion!
