### ISSUE TITLE
Timeout in ZMQLeaderServer serve

### ISSUE THREAD

**Issue by johnny-wang16** [wuphilipp/gello_software#7]
Hi there,

I've successfully ran the script: `python scripts/gello_get_offset.py ` and copied the output joint offset list to `gello/agents/gello_agent.py`. However, Im unable to control the simulated franka robot. Running `python experiments/launch_nodes.py --robot sim_panda` gives me the following message : `Timeout in ZMQLeaderServer serve`  and subsequently running this command: `python experiments/run_env.py --agent=gello` gives me the following message and ends imeediately:

```
UserWarning: The field robot_type is annotated with type <class 'str'>, but the default value None has type <class 'NoneType'>. We'll try to handle this gracefully, but it may cause unexpected behavior.
  warnings.warn(
Found 1 ports
using port /dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FT89FJHP-if00-port0
attempting to connect to port: /dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FT89FJHP-if00-port0
Going to start position

joint[0]: 	 delta: 1.166 , leader: 	-1.166 , follower: 	0.000
joint[1]: 	 delta: 0.904 , leader: 	0.904 , follower: 	0.000
joint[2]: 	 delta: 2.599 , leader: 	-2.599 , follower: 	0.000
joint[3]: 	 delta: 1.681 , leader: 	1.681 , follower: 	0.000
joint[4]: 	 delta: 5.031 , leader: 	-5.031 , follower: 	0.000
joint[5]: 	 delta: 2.425 , leader: 	-2.425 , follower: 	0.000
joint[6]: 	 delta: 2.549 , leader: 	-2.549 , follower: 	0.000
joint[7]: 	 delta: 1.000 , leader: 	1.000 , follower: 	0.000

```

Could you suggest some potential source of bugs that might cause this error?

**Comment by johnny-wang16** [comment]
I figured it out. This situation is due to improper calibration. When running `python scripts/gello_get_offset.py ` make sure gello is in the same configuration as what you set. I set everything to 0 just to be simple. 

The reason why running this command: `python experiments/run_env.py --agent=gello` exits immediately is because [this line of code](https://github.com/wuphilipp/gello_software/blob/e6a660da6d13822d69cf96617b2448aecd1e1335/experiments/run_env.py#L157) that sets a threshold for the action value. The action values might be too large due to inaccurate calibration so you have to repeatedly run `python experiments/run_env.py --agent=gello` and adjust the joint positions until it's smaller than 0.8. If the gripper value stays at 1, it's probably because the gripper open/close values from `python scripts/gello_get_offset.py `  is not copied to the configuration.

**Comment by itsmuffintimeee** [comment]
Thanks.
